
const en = {
  name:'en',
  language: 'en-EN',
  library: 'LIBRARY',
  home: 'HOME',
  placeholder: 'Search movies',
  messageFailure: 'Search result not successful. Enter the correct movie name and try again',
  day: 'DAY',
  week: 'WEEK',
  top: 'top rated',
  upcoming: 'upcoming',
  footerText1: '© 2021 | All Rights Reserved | Developed with ',
  footerText2: 'by',
  watched: 'WATCHED',
  queue: 'queue',
  addToWatched: 'add To Watched',
  addToQueue: 'add To Queue',
  removeFromWatched: `remove from watched`,
  removeFromQueue: `remove from QUEUE`,
  openTrailer: 'open Trailer',
  btn: 'EnBtn',
};

const ru = {
  name:'ru',
  language: 'ru-RU',
  library: 'БИБЛИОТЕКА',
  home: 'ГЛАВНАЯ',
  placeholder: 'Поиск фильмов',
  messageFailure: 'Поиск не дал результатов. Введите корректное название фильма и попробуйте ещё раз',
  day: 'ДЕНЬ',
  week: 'НЕДЕЛЯ',
  top: 'ПОПУЛЯРНЫЕ',
  upcoming: 'ПРЕМЬЕРА',
  footerText1: ' © 2021 | Все права защищены | Создано c',
  footerText2: '',
  watched: 'ПРОСМОТРЕНЫЕ',
  queue: 'ПРОCМОТРЕТЬ',
  addToWatched: 'добавить в ПРОСМОТРЕНЫЕ',
  addToQueue: 'просмотреть позже',
  removeFromWatched: `удалить с просмотренных`,
  removeFromQueue: `удалить с просмотра`,
  openTrailer: 'трейлер',
  btn: 'RuBtn',
};

const ua = {
  name:'ua',
  language: 'uk-UA',
  library: 'БІБЛІОТЕКА',
  home: 'ГОЛОВНА',
  placeholder: 'Пошук фільмів',
  messageFailure: 'Результат пошуку невдалий. Введіть коректну назву фільму і спробуйте ще раз',
  day: 'ДЕНЬ',
  week: 'НЕДіЛЯ',
  top: 'ПОПУЛЯНІ',
  upcoming: "ПРЕМ'ЄРА",
  footerText1: ' © 2021 | Всі права захищені | Створено з',
  footerText2: '',
  watched: 'ПЕРЕГЛЯНУТІ',
  queue: 'до перегляду',
  addToWatched: `додати в переглянуті`,
  addToQueue: `додати до перегляду`,
  removeFromWatched: `видалити з переглянутих`,
  removeFromQueue: `видалити з перегляду`,
  openTrailer: 'трейлер',
  btn: 'UaBtn',
};

export {ua, en, ru}