
const en = {
  language: 'en-EN',
  library: 'LIBRARY',
  home: 'HOME',
  placeholder: 'Search movies',
  messageFailure: 'Search result not successful. Enter the correct movie name and try again',
  day: 'DAY',
  week: 'WEEK',
  top: 'top rated',
  upcoming: 'upcoming',
  footerText1: '© 2021 | All Rights Reserved | Developed with ',
  footerText2: 'by',
  watched: 'WATCHED',
  queue: 'queue',
  addToWatched: 'add To Watched',
  addToQueue: 'add To Queue',
  removeFromWatched: `remove from watched`,
  removeFromQueue: `remove from QUEUE`,
  openTrailer: 'open Trailer',
  emptyLibrary: "You haven't added any movies yet",
  footerGoitText: 'GoIT Students',
  aboutTitle: 'About',
  vote: 'Vote / Votes',
  popularity: 'Popularity',
  title: 'Original Title',
  genre: 'Genre',
  btn: 'EnBtn',
  langIcon: 'Choose language',
};

const ru = {
  language: 'ru-RU',
  library: 'БИБЛИОТЕКА',
  home: 'ГЛАВНАЯ',
  placeholder: 'Поиск фильмов',
  messageFailure: 'Поиск не дал результатов. Введите корректное название фильма и попробуйте ещё раз',
  day: 'ДЕНЬ',
  week: 'НЕДЕЛЯ',
  top: 'ПОПУЛЯРНЫЕ',
  upcoming: 'ПРЕМЬЕРА',
  footerText1: ' © 2021 | Все права защищены | Создано c',
  footerText2: '',
  watched: 'ПРОСМОТРЕНЫЕ',
  queue: 'ПРОCМОТРЕТЬ',
  addToWatched: 'добавить в ПРОСМОТРЕНЫЕ',
  addToQueue: 'просмотреть позже',
  removeFromWatched: `удалить с просмотренных`,
  removeFromQueue: `удалить с просмотра`,
  openTrailer: 'трейлер',
  emptyLibrary: "Вы еще не добавили ни одного фильма",
  footerGoitText: ' студентами GoIT',
  aboutTitle: 'О фильме',
  vote: 'Рейтинг',
  popularity: 'Популярность',
  title: 'Название',
  genre: 'Жанр',
  langIcon: 'Выбрать язык',
  btn: 'RuBtn',
};

const ua = {
  language: 'uk-UA',
  library: 'БІБЛІОТЕКА',
  home: 'ГОЛОВНА',
  placeholder: 'Пошук фільмів',
  messageFailure: 'Результат пошуку невдалий. Введіть коректну назву фільму і спробуйте ще раз',
  day: 'ДЕНЬ',
  week: 'НЕДіЛЯ',
  top: 'ПОПУЛЯНІ',
  upcoming: "ПРЕМ'ЄРА",
  footerText1: ' © 2021 | Всі права захищені | Створено з',
  footerText2: '',
  watched: 'ПЕРЕГЛЯНУТІ',
  queue: 'до перегляду',
  addToWatched: `додати в переглянуті`,
  addToQueue: `додати до перегляду`,
  removeFromWatched: `видалити з переглянутих`,
  removeFromQueue: `видалити з перегляду`,
  openTrailer: 'трейлер',
  emptyLibrary: "Ви ще не додали жодного фільму",
  footerGoitText: ' студентами GoIT',
  aboutTitle: 'Про фільм',
  vote: 'Рейтинг',
  popularity: 'Популярність',
  title: 'Назва',
  genre: 'Жанр',
  langIcon: 'Обрати мову',
  btn: 'UaBtn',
};

const es = {
  language: 'es-ES',
    library: 'Mi lista',
    home: 'inicio',
    placeholder: 'Buscar películas',
    messageFailure:
      'La búsqueda no ha dado ningún resultado. Ingrese el nombre correcto de la película y vuelva a intentarlo',
    day: 'día',
    week: 'semana',
    top: 'popular',
    upcoming: 'novedades',
    footerText1: ' © 2021 | Todos los derechos reservados | Creado con',
    footerText2: '',
    watched: 'visto',
    queue: 'cola',
    addToWatched: 'añadir a vistos',
    addToQueue: 'añadir a cola',
    openTrailer: 'tráiler',
    removeFromWatched: 'Eliminar de visto',
    removeFromQueue: 'eliminar de cola',
    emptyLibrary: 'Todavía no tienes ninguna película añadida',
    footerGoitText: 'GoIT estudiante',
    aboutTitle:'Sobre la película',
    vote:  'Voto / Votos',
    popularity: 'Popularidad',
    title: 'Título',
    genre: 'Género',
    langIcon: 'Elige lengua',
    btn: 'EsBtn',
  }
  

export { ua, en, ru, es }