export default {
  galleryRef: document.querySelector('[data-modal-open]'),
  searchFormRef: document.querySelector('.search-form'),
  searchInputRef: document.querySelector('.search-form__input'),
  messageFailure: document.querySelector('.message-failure'),
  btnDay: document.querySelector('[data-button-day]'),
  btnWeek: document.querySelector('[data-button-week]'),
  btnTop: document.querySelector('[data-button-top]'),
  btnUpcoming: document.querySelector('[data-button-upcoming]'),
  headerBtns: document.querySelector('.header-menu-btn'),
  myLibraryRef: document.querySelector('.js-link-library'),
  homeRef: document.querySelector('.js-link-home'),
  libraryBtns: document.querySelector('[data-value="library-btns"]'),
  modalRef: document.querySelector('.js-lightbox'),
  overlay: document.querySelector('.lightbox__overlay'),
  headerBackgroundImageRef: document.querySelector('.header-background-img'),
  periodBtnBox: document.querySelector('.period-buttons'),
  paginationBox: document.querySelector('.tui-pagination'),
  watchedBtn: document.querySelector('[data-value="watched"]'),
  queueBtn: document.querySelector('[data-value="queue"]'),
  buttonClose: document.querySelector('.lightbox__button'),
  content: document.querySelector('.lightbox__content'),
  EnBtn: document.getElementById('en-btn'),
  UaBtn: document.getElementById('ua-btn'),
  RuBtn: document.getElementById('ru-btn'),
  EsBtn: document.getElementById('es-btn'),
  langBtns:document.querySelector('.lang'),
  footerGoitText: document.querySelector('.footer-wrapper__underline'),
  footerText1: document.querySelector('.footer-wrapper__text--rights'),
  footerText2: document.querySelector('.footer-wrapper__text--by'),
  logoLink: document.querySelector('.nav-menu__logo-link'),
  langIcon: document.querySelector('.nav-menu__link--icon'),
};
